name: Rust

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: thumbv7em-none-eabihf

      - name: Check compilation
        run: cargo check --verbose

      - name: Build firmware (dev profile)
        run: cargo build --verbose

      - name: Build firmware (release profile)
        run: cargo build --release --verbose

